Month 9/step 1
phillharmonia/react-burger pull request #5
Opened 2023-03-11 12:55 UTC by phillharmonia

2023-03-11 13:27 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
Что понравилось:
- Для form используется событие `onSubmit`
- Роутинг настроен и работает корректно.
- Есть защита роутов для авторизованных и не авторизованных юзеров.

Что необходимо исправить:
- Если неавторизованный пользователь пытается сделать заказ, то хорошо бы его переадресовать на страницу логина, а после авторизации вернуть обратно на страницу с конструктором.
- После успешного прохождения запроса на регистрацию необходимо переводить юзера на главную страницу под авторизованных акаунтом.
- После перезагрузки пропадает авторизация
- Кнопки "Отмена" и "Сохранить" должны быть скрыты или задизейблены до тех пор, пока юзер не внесет изменения в форму.
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.
- Роут `/reset-password` должен быть доступен только через роут `/forgot-password`.
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью ` return <Redirect to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Redirect`)

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-11 13:27 UTC, andryxxa93 commented on src/components/App/App.jsx
> +                    <Route path="/login" element={<LoginPage />}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-11 13:27 UTC, andryxxa93 commented on src/page/Login/Login.jsx
> +    if (user) {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-03-14 05:36 UTC, andryxxa93 commented
Отличная работа! Но осталось еще несколько небольших замечаний:

- При оформлении заказа айди булок не попадает в тело запроса
<img width="1440" alt="Снимок экрана 2023-03-14 в 08 30 23" src="https://user-images.githubusercontent.com/60173362/224905214-62f75f94-11e9-45b2-8f2e-24c46d30d6e1.png">

- При попытке попасть на роут с регистрацией перекидывает на главную страницу.

https://user-images.githubusercontent.com/60173362/224905498-c269ef0e-f48a-4e63-a69b-821466ad870b.mov

- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. 

<img width="922" alt="Снимок экрана 2023-03-14 в 08 33 41" src="https://user-images.githubusercontent.com/60173362/224905680-d81269c7-21d0-4eac-9e97-35eedbc96d02.png">

**Можно лучше**
- Если токена в куках нет, то нет смысла и пытаться получить данные юзера.

<img width="1440" alt="Снимок экрана 2023-03-14 в 08 28 21" src="https://user-images.githubusercontent.com/60173362/224904888-2bf7d058-b4b7-4d80-9482-764a7a2f9a1a.png">

2023-03-14 08:22 UTC, phillharmonia commented
При попытке попасть на роут с регистрацией перекидывает на главную страницу.
У меня нет с этим проблем до авторизации, после авторизации и выхода тоже нет
https://user-images.githubusercontent.com/106474343/224939086-3f5f15c7-06cf-4808-ba52-6a702b8e231e.mp4

2023-03-14 15:48 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-18 07:54 UTC, merged